# Generated by Django 4.1.5 on 2023-03-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('head0', models.CharField(default='', max_length=500)),
                ('chead0', models.CharField(default='', max_length=5000)),
                ('head1', models.CharField(default='', max_length=500)),
                ('chead1', models.CharField(default='', max_length=5000)),
                ('head2', models.CharField(default='', max_length=500)),
                ('chead2', models.CharField(default='', max_length=5000)),
                ('head3', models.CharField(default='', max_length=500)),
                ('chead3', models.CharField(default='', max_length=5000)),
                ('features', models.CharField(default='', max_length=500)),
                ('cfeatures', models.CharField(default='', max_length=5000)),
                ('pub_date', models.DateField()),
                ('tumbnail', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
