# Generated by Django 4.1.5 on 2023-01-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_stock_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
